remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/light.css"
locale: en-US
title: "2020 Capstone"
url: "https://neghena.github.io"
baseurl: "GPS_Autonomous_Nav/"
mathjax:
  enable: true
